name: Create approval in Merkely
on:
  workflow_dispatch:
    inputs:
      deploy_commit:
        description: 'Git commit-ish to approve'
        required: true
        default: 'master'

jobs:
  create_approval_in_merkely:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # fetch full history
        fetch-depth: 0
        ref: ${{ github.event.inputs.deploy_commit }}


    - name: Make Docker image name available for following step
      run: |
        echo "TAGGED_IMAGE=${{ secrets.DOCKERHUB_REPO_OWNER }}/loancalculator:$(git log -1 --pretty=%h)" >> ${GITHUB_ENV}


    - env:
        MERKELY_FINGERPRINT: docker://${TAGGED_IMAGE}
        MERKELY_TARGET_SRC_COMMITISH: ${{ github.event.inputs.deploy_commit }}
        MERKELY_BASE_SRC_COMMITISH: origin/production
        MERKELY_DESCRIPTION: "Approval created by ${GITHUB_ACTOR} on github"
        MERKELY_IS_APPROVED: 'TRUE'
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
      run: |
        make docker_pull
        make merkely_log_approval




